"use client";
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import type { StudioUser,StudioWorkspace,StudioProjectSummary } from '@/lib/studio/types';
import { emptyStudy } from '@/lib/studio/project-copy';
import { studioApi,StudioApiError } from './client';
import { SettingsDialog,useStudioPreferences } from './preferences';
import s from './projects.module.css';

export default function StudioHome({embedded=false}:{embedded?:boolean}){
 const router=useRouter(),search=useRef<HTMLInputElement>(null);
 const [user,setUser]=useState<StudioUser|null>(null),[configured,setConfigured]=useState(true),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [mode,setMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pendingEmail,setPendingEmail]=useState(''),[resendWait,setResendWait]=useState(0);
 const [projects,setProjects]=useState<StudioProjectSummary[]>([]),[query,setQuery]=useState(''),[section,setSection]=useState<'recent'|'all'|'archived'>('recent'),[settings,setSettings]=useState(false),[newProject,setNewProject]=useState(false),[title,setTitle]=useState(''),[rename,setRename]=useState<StudioProjectSummary|null>(null),[sampleRequested,setSampleRequested]=useState(false);
 const {preferences,update,style}=useStudioPreferences();
 async function refresh(){const result=await studioApi<{workspaces:StudioProjectSummary[]}>('/api/studio/workspaces');setProjects(result.workspaces);}
 useEffect(()=>{let cancelled=false;const params=new URLSearchParams(window.location.search);setSampleRequested(params.has('sample'));setNewProject(params.has('new'));studioApi<{user:StudioUser|null;configured:boolean}>('/api/studio/auth').then(async data=>{if(cancelled)return;setConfigured(data.configured);setUser(data.user);if(data.user){const result=await studioApi<{workspaces:StudioProjectSummary[]}>('/api/studio/workspaces');if(!cancelled)setProjects(result.workspaces);}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!resendWait)return;const timer=setInterval(()=>setResendWait(n=>Math.max(0,n-1)),1000);return()=>clearInterval(timer);},[resendWait]);
 useEffect(()=>{if(!user)return;const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='p'){e.preventDefault();search.current?.focus();}};window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[user]);
 async function resend(){if(!pendingEmail||busy||resendWait)return;setBusy(true);setError('');try{await studioApi('/api/studio/auth',{method:'POST',body:JSON.stringify({action:'resend',email:pendingEmail})});setNotice(`Confirmation requested for ${pendingEmail}. Check your inbox and spam folder.`);setResendWait(60);}catch(e){if(e instanceof StudioApiError&&e.body.error==='rate_limited')setResendWait(60);setError(e instanceof Error?e.message:'Could not send confirmation.');}finally{setBusy(false);}}
 async function authenticate(){setBusy(true);setError('');setNotice('');try{const result=await studioApi<{user?:StudioUser;requiresEmailConfirmation?:boolean}>('/api/studio/auth',{method:'POST',body:JSON.stringify({action:mode,email,password})});setPassword('');if(result.user&&!result.requiresEmailConfirmation){const current=await studioApi<{user:StudioUser|null}>('/api/studio/auth');setUser(current.user);if(current.user)await refresh();}else{setPendingEmail(email.trim());setMode('signin');setResendWait(60);setNotice(`Confirm the email sent to ${email.trim()} to finish registration.`);}}catch(e){if(e instanceof StudioApiError&&e.body.error==='email_not_confirmed')setPendingEmail(email.trim());setError(e instanceof Error?e.message:'Could not sign in.');}finally{setBusy(false);}}
 async function create(sample=false){if(!sample&&!title.trim())return;setBusy(true);setError('');try{const {workspace}=await studioApi<{workspace:StudioWorkspace}>('/api/studio/workspaces',{method:'POST',body:JSON.stringify(sample?{sampleId:'intentional-action'}:{document:emptyStudy(title.trim())})});router.push(`/build/${workspace.id}`);}catch(e){setError(e instanceof Error?e.message:'Could not create project.');await refresh().catch(()=>undefined);}finally{setBusy(false);}}
 async function action(project:StudioProjectSummary,action:string,nextTitle?:string){setBusy(true);setError('');try{const result=await studioApi<{workspace:StudioWorkspace}>(`/api/studio/workspaces/${project.id}/project`,{method:'POST',body:JSON.stringify({action,revision:project.revision,title:nextTitle})});if(action==='fork'){router.push(`/build/${result.workspace.id}`);return;}setRename(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Project operation failed.');await refresh().catch(()=>undefined);}finally{setBusy(false);}}
 async function signout(){setBusy(true);try{await studioApi('/api/studio/auth',{method:'POST',body:JSON.stringify({action:'signout'})});setUser(null);setProjects([]);setPassword('');}catch(e){setError(e instanceof Error?e.message:'Could not sign out.');}finally{setBusy(false);}}
 const filtered=projects.filter(p=>Boolean(p.project?.archived)===(section==='archived')&&p.title.toLowerCase().includes(query.trim().toLowerCase()));
 const visible=section==='recent'&&!query?filtered.slice(0,12):filtered;
 return <div className={`${s.hub} ${embedded?s.embedded:''}`} data-theme={preferences.theme} data-density={preferences.density} style={style}>
  {!embedded&&<header className={s.hubHeader}><Link href="/">HumanStudy-Hub</Link><span>{user?'Projects':'Build Study'}</span><button onClick={()=>setSettings(true)}>Settings</button></header>}
  {loading?<main className={s.authLayout}><p role="status">Loading your workspace…</p></main>:!user?<main className={s.authLayout}><div className={s.authIntro}><h1>Your study,<br/>one workspace.</h1><p>Sources, Human Program, and your study agent.</p><div className={s.authPreview}><span>Resources</span><span>Human Program</span><span>Study agent</span></div>{sampleRequested&&<p>Sign in to load an editable sample.</p>}</div><section className={s.authCard}><h2>{mode==='signin'?'Sign in':'Create your account'}</h2>{!configured?<p>Account storage is unavailable. Please try again later.</p>:<><form onSubmit={e=>{e.preventDefault();void authenticate();}}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label>Password<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label>{mode==='signup'&&<small>At least 8 characters. We’ll email you a confirmation link.</small>}<button className={s.primary} disabled={busy}>{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button></form><button className={s.textButton} disabled={busy} onClick={()=>{setMode(mode==='signin'?'signup':'signin');setError('');}}>{mode==='signin'?'Create an account':'Already have an account? Sign in'}</button>{pendingEmail&&<button className={s.textButton} disabled={busy||resendWait>0} onClick={()=>void resend()}>{resendWait?`Resend in ${resendWait}s`:'Resend confirmation email'}</button>}</>}{error&&<p role="alert" className={s.error}>{error}</p>}{notice&&<p role="status" className={s.notice}>{notice}</p>}</section></main>:<div className={s.projectLayout}><aside className={s.projectNav}><strong>Workspace</strong>{(['recent','all','archived'] as const).map(item=><button key={item} aria-current={section===item?'page':undefined} onClick={()=>setSection(item)}>{item==='recent'?'Recent':item==='all'?'All projects':'Archived'}</button>)}<footer><span title={user.email}>{user.email}</span><button onClick={()=>setSettings(true)}>Settings</button><button disabled={busy} onClick={()=>void signout()}>Sign out</button></footer></aside><main className={s.projectMain}><div className={s.projectHeading}><h1>{section==='archived'?'Archived projects':'Projects'}</h1><div><button disabled={busy} onClick={()=>void create(true)}>{busy?'Working…':'Load sample'}</button><button className={s.primary} disabled={busy} onClick={()=>{setNewProject(true);setTitle('');}}>＋ New project</button></div></div><input ref={search} className={s.projectSearch} aria-label="Find a project" placeholder="Find a project…" value={query} onChange={e=>setQuery(e.target.value)}/>
  {sampleRequested&&<div className={s.sampleCard}><div><strong>Intentional Action and Side-Effects</strong><p>Original paper, Human Program, and vignette materials.</p></div><button className={s.primary} disabled={busy} onClick={()=>void create(true)}>Load sample</button></div>}
  {newProject&&<form className={s.newProject} onSubmit={e=>{e.preventDefault();void create();}}><input autoFocus required aria-label="Project name" placeholder="Project name" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/><button className={s.primary} disabled={busy||!title.trim()}>Create</button><button type="button" onClick={()=>setNewProject(false)}>Cancel</button></form>}
  {rename&&<form className={s.newProject} onSubmit={e=>{e.preventDefault();void action(rename,'rename',title);}}><input autoFocus required aria-label="Rename project" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/><button className={s.primary} disabled={busy||!title.trim()}>Save name</button><button type="button" onClick={()=>setRename(null)}>Cancel</button></form>}
  {error&&<p role="alert" className={s.error}>{error}</p>}
  <div className={s.projectList}>{!visible.length?<div className={s.empty}><h2>{query?'No matching projects':section==='archived'?'No archived projects':'Start a project'}</h2>{!query&&section!=='archived'&&<p>Add your paper, or load a sample and make it your own.</p>}</div>:visible.map(p=><article key={p.id}><Link href={`/build/${p.id}`}><strong>{p.title}</strong><small>{p.project?.forkedFrom?'Fork · ':''}{p.project?.sampleId?'Sample · ':''}{new Date(p.updated_at).toLocaleDateString()}</small></Link>{(p.project?.copyState==='failed'||p.project?.copyState==='preparing'&&Date.now()-Date.parse(p.updated_at)>120_000)&&<button disabled={busy} onClick={()=>void action(p,'retry-copy')}>Retry file copy</button>}<details className={s.projectMenu}><summary aria-label={`Actions for ${p.title}`}>···</summary><div><button disabled={busy} onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');setRename(p);setTitle(p.title);}}>Rename</button><button disabled={busy||p.project?.copyState==='preparing'||p.project?.copyState==='failed'} onClick={()=>void action(p,'fork')}>Fork</button><button disabled={busy} onClick={()=>void action(p,p.project?.archived?'restore':'archive')}>{p.project?.archived?'Restore':'Archive'}</button><a href={`/api/studio/workspaces/${p.id}/export`}>Export</a></div></details></article>)}</div></main></div>}
  {settings&&<SettingsDialog onClose={()=>setSettings(false)} preferences={preferences} onChange={update}/>}
 </div>;
}
