"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { HubMark } from '@/app/build-preview/ui';
import type { StudioDocument,StudioUser,StudioWorkspace } from '@/lib/studio/types';
import { studioApi,StudioApiError } from './client';
import s from './studio.module.css';
export default function StudioHome(){
 const router=useRouter();const [user,setUser]=useState<StudioUser|null>(null),[configured,setConfigured]=useState(true),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[mode,setMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[title,setTitle]=useState(''),[workspaces,setWorkspaces]=useState<StudioWorkspace[]>([]);
 useEffect(()=>{let cancelled=false;studioApi<{user:StudioUser|null;configured:boolean}>('/api/studio/auth').then(async data=>{if(cancelled)return;setConfigured(data.configured);setUser(data.user);if(data.user){const list=await studioApi<{workspaces:StudioWorkspace[]}>('/api/studio/workspaces');if(!cancelled)setWorkspaces(list.workspaces);}}).catch(e=>{if(cancelled)return;if(e instanceof StudioApiError&&e.body.error==='setup_required')setConfigured(false);else setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
 async function authenticate(){setBusy(true);setError('');setNotice('');try{const result=await studioApi<{user?:StudioUser;requiresEmailConfirmation?:boolean;message?:string}>('/api/studio/auth',{method:'POST',body:JSON.stringify({action:mode,email,password})});setPassword('');if(result.user&&!result.requiresEmailConfirmation){const current=await studioApi<{user:StudioUser|null}>('/api/studio/auth');setUser(current.user);if(current.user){setWorkspaces((await studioApi<{workspaces:StudioWorkspace[]}>('/api/studio/workspaces')).workspaces);}else setNotice('Check your email to confirm your account, then sign in.');}else setNotice(result.message||'Check your email to confirm your account, then sign in.');}catch(e){setError(e instanceof Error?e.message:'Could not sign in.');}finally{setBusy(false);}}
 async function createStudy(){if(!title.trim())return;setBusy(true);setError('');const name=title.trim();const document:StudioDocument={version:1,title:name,model:{id:crypto.randomUUID(),title:name,source:{title:'',authors:'',filename:''},entities:[],relations:[],procedure:[],variables:[]},sources:[],annotations:[],conversations:[],reviewResponses:{}};try{const {workspace}=await studioApi<{workspace:StudioWorkspace}>('/api/studio/workspaces',{method:'POST',body:JSON.stringify({document})});router.push(`/build/${workspace.id}`);}catch(e){setError(e instanceof Error?e.message:'Could not create study.');setBusy(false);}}
 return <div className={s.home}><header><Link href="/" className={s.brand}><HubMark/>Human Study Hub</Link><span>Build Study</span><Link className={s.legacy} href="/pipeline">Legacy pipeline ↗</Link>{user&&<button onClick={async()=>{setBusy(true);setError('');try{await studioApi('/api/studio/auth',{method:'POST',body:JSON.stringify({action:'signout'})});setUser(null);setWorkspaces([]);}catch(error){setError(error instanceof Error?error.message:'Could not sign out.');}finally{setBusy(false);}}}>Sign out</button>}</header><main>{loading?<p>Loading your workspace…</p>:!configured?<section className={s.setup}><h1>Connect the workspace service</h1><p>The new platform needs its account database and private file storage configured.</p><code>SUPABASE_URL<br/>SUPABASE_PUBLISHABLE_KEY</code><p>Apply the SQL migration in this branch before using accounts. The interface preview remains available.</p><Link href="/build-preview">Open interface preview ↗</Link></section>:!user?<section className={s.auth}><span>YOUR RESEARCH WORKSPACE</span><h1>{mode==='signin'?'Welcome back.':'Start a research workspace.'}</h1><p>Keep your sources, study model and conversations together.</p><form onSubmit={e=>{e.preventDefault();authenticate();}}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button></form><button className={s.textButton} onClick={()=>{setMode(mode==='signin'?'signup':'signin');setError('');}}>{mode==='signin'?'Create an account':'Already registered? Sign in'}</button></section>:<section className={s.projects}><span>{user.email}</span><h1>Your studies</h1><form onSubmit={e=>{e.preventDefault();createStudy();}}><input aria-label="New study title" placeholder="Name a study…" maxLength={160} required value={title} onChange={e=>setTitle(e.target.value)}/><button disabled={busy||!title.trim()}>＋ New study</button></form><div>{workspaces.length===0?<p>Create a study, add a paper, and develop the model with the agent.</p>:workspaces.map(w=><Link key={w.id} href={`/build/${w.id}`}><strong>{w.title}</strong><small>{new Date(w.updated_at).toLocaleDateString()} · Revision {w.revision}</small><span>↗</span></Link>)}</div></section>}{error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p className={s.notice} role="status">{notice}</p>}</main></div>;
}
