/** A reviewable study representation. Source claims and implementation choices stay separate. */
import type { HumanProgram } from "@/lib/studio/human-program";
export type Rect = { x: number; y: number; w: number; h: number };
export type Evidence = { sourceId?: string; page: number; rects: Rect[]; quote: string };
export type EntityKind = "background" | "hypothesis" | "design" | "participants" | "material" | "procedure" | "record" | "variable" | "analysis" | "result";
export type Entity = {
  id: string; kind: EntityKind; title: string; subtitle: string;
  description: string; evidence: Evidence; studyIds?:string[]; fields: { id?:string; name: string; value: string; status?: "reported" | "implementation" | "unresolved" }[];
  x: number; y: number; w: number; h: number;
};
export type Variable = { id: string; name: string; role: string; type: string; unit: string; producedBy: string; usedBy: string; definition: string; status: "reported" | "implementation" | "unresolved"; entity: string };
export type StudyReviewIssue = {
  id: string; title: string; severity: "blocking" | "decision" | "check";
  reason: string; impact: string; suggestedAction: string;
  entity?: string; study?: string; field?: string; sourcePointer?: string; evidence?: Evidence;
};
export type StudySchema = {
  program?:HumanProgram;
  id: string; title: string; source: { title: string; authors: string; filename: string };
  entities: Entity[]; relations: { from: string; to: string; label: string }[];
  procedure: { id: string; entity?:string; name: string; input: string; actor: string; output: string; evidence: Evidence }[];
  variables: Variable[];
  reviewIssues?: StudyReviewIssue[];
};
const assignmentEvidence: Evidence = { page:3,rects:[{x:8.9,y:51.8,w:39.4,h:7.8}],quote:"There were two versions of the questionnaire, each with high anchors for some quantities and low anchors for the others. The quantities appeared in the same order in all questionnaires." };
const trialEvidence:Evidence={page:2,rects:[{x:51.1,y:87.3,w:40.1,h:6.2}],quote:"Experimental subjects (n = 103) answered three consecutive questions about each of the 15 quantities. They first indicated whether the quantity was greater or less than an anchor value; next, they estimated the quantity;"};
export const study:StudySchema={
 id:"jacowitz-kahneman-1995",title:"Measures of Anchoring in Estimation Tasks",
 source:{title:"Measures of Anchoring in Estimation Tasks",authors:"Jacowitz & Kahneman · 1995",filename:"jacowitz-kahneman-1995-measures-of-anchoring-in-estimation-tasks.pdf"},
 entities:[
 {"id": "rationale", "kind": "background", "title": "Why measure anchoring?", "subtitle": "Quantify how numerical anchors shift estimates.", "description": "The paper proposes a comparable measure of anchoring across estimation questions, using an independent calibration distribution.", "evidence": {"page": 2, "rects": [], "quote": "Anchoring effects are generally believed to be large and reliable. But how large is large?"}, "fields": [{"name": "Research question", "value": "How much do numerical anchors shift estimates?", "status": "implementation"}, {"name": "Purpose", "value": "Measure the magnitude of anchoring across different quantities.", "status": "reported"}], "x": 20, "y": 0, "w": 205, "h": 78},
 {"id": "confidence-prediction", "kind": "hypothesis", "title": "Confidence and anchoring", "subtitle": "Lower confidence → stronger susceptibility to anchors.", "description": "A conditional prediction explicitly discussed in the paper. It is distinct from the primary high/low anchoring contrast and is not represented as a preregistered hypothesis.", "evidence": {"page": 5, "rects": [], "quote": "If susceptibility to anchoring is associated with low confi- dence, the correlation between estimates and confi- dence ratings should be negative when the anchor is high and positive when the anchor is low."}, "fields": [{"name": "Prediction", "value": "Estimate–confidence correlations are negative for high anchors and positive for low anchors.", "status": "reported"}, {"name": "Test", "value": "Correlations computed for each item and anchor level.", "status": "reported"}], "x": 280, "y": 0, "w": 220, "h": 78},
 {id:"people",kind:"participants",title:"Who takes part",subtitle:"53 calibration · 103 experimental",x:20,y:35,w:205,h:78,description:"Separate calibration participants from experimental participants. An experimental participant answers all 15 items. Anchor level belongs to the item in their questionnaire version; do not model each participant as permanently high-anchor or low-anchor.",evidence:{page:2,rects:[{x:51.1,y:67.3,w:40.2,h:6.2},{x:51.1,y:73.5,w:40.2,h:13.5},{x:51.1,y:87.3,w:40.2,h:3.2}],quote:"Subjects were 156 students at the University of California, Berkeley"},fields:[{name:"Population",value:"UC Berkeley students",status:"reported"},{name:"Calibration sample",value:"n = 53",status:"reported"},{name:"Experimental sample",value:"n = 103",status:"reported"},{name:"Participant identity",value:"participant_id",status:"implementation"}]},
 {id:"inputs",kind:"material",title:"What they receive",subtitle:"15 quantities · 2 questionnaire versions",x:280,y:35,w:220,h:78,description:"A questionnaire version maps each of 15 items to a low or high anchor. Both versions use the same item order. Low and high anchors come from the 15th and 85th percentiles of calibration estimates. Allocation to versions is not specified in the quoted passage.",evidence:assignmentEvidence,fields:[{name:"Input record",value:"item_id, question, unit, low_anchor, high_anchor",status:"implementation"},{name:"Anchor construction",value:"Calibration percentiles: 15th / 85th",status:"reported"},{name:"Version mapping",value:"version × item → anchor_level",status:"implementation"},{name:"Version allocation",value:"Needs source review",status:"unresolved"}]},
 {id:"procedure",kind:"procedure",title:"What happens, in order",subtitle:"Compare → estimate → confidence",x:135,y:185,w:250,h:90,description:"For each quantity, present the assigned anchor, collect a greater/less judgment, then a numerical estimate, then confidence. Keep the sequence and the same order of items across questionnaires.",evidence:trialEvidence,fields:[{name:"Actor",value:"One experimental participant",status:"reported"},{name:"Repeats over",value:"15 quantities, fixed item order",status:"reported"},{name:"Visible input",value:"Current item + anchor from questionnaire version",status:"implementation"},{name:"Steps",value:"Comparison → estimate → confidence",status:"reported"}]},
 {id:"responses",kind:"record",title:"What gets recorded",subtitle:"One row per participant × item",x:135,y:350,w:250,h:78,description:"Keep comparison, numerical estimate and confidence as distinct observed responses, with the participant, item and version identifiers needed to reconstruct the trial. The row layout is an implementation proposal, not a table printed in the paper.",evidence:{page:3,rects:[{x:8.9,y:51.8,w:39.5,h:1.6}],quote:"then they indicated their confidence in the estimate."},fields:[{name:"Grain",value:"participant × item",status:"implementation"},{name:"Keys",value:"participant_id, item_id, questionnaire_version",status:"implementation"},{name:"Observed responses",value:"comparison, estimate, confidence",status:"reported"},{name:"Preserve",value:"Raw response and parsing status",status:"implementation"}]},
 {id:"manipulation",kind:"variable",title:"anchor_level",subtitle:"Manipulation · low / high · per item",x:20,y:505,w:230,h:72,description:"Anchor level is a categorical variable on a participant–item observation, determined by questionnaire version and item. An anchor's numerical value has the unit of its corresponding quantity.",evidence:assignmentEvidence,fields:[{name:"Statistical role",value:"Manipulated factor",status:"reported"},{name:"Type / levels",value:"Categorical · low, high",status:"reported"},{name:"Unit of variation",value:"Item within questionnaire version",status:"reported"}]},
 {id:"outcome",kind:"variable",title:"estimate → percentile",subtitle:"Observed quantity → derived outcome",x:285,y:505,w:235,h:72,description:"Transform each estimate into the corresponding percentile of that item's calibration distribution. The paper assigns 0 or 100 to estimates outside the calibration range. Keep raw and transformed values separately.",evidence:{page:2,rects:[{x:51.1,y:23.7,w:40.2,h:24.8}],quote:"we transform all estimates into the corresponding percentiles in the calibration group"},fields:[{name:"Observed value",value:"estimate · numeric, item-specific units",status:"reported"},{name:"Derived value",value:"estimate_percentile · 0–100",status:"reported"},{name:"Reference",value:"Same item's calibration distribution",status:"reported"},{name:"Transformation",value:"Percentile; out-of-range values → 0 / 100",status:"reported"}]},
 {id:"analysis",kind:"analysis",title:"Which comparison is made",subtitle:"Anchoring index + transformed-score contrast",x:105,y:675,w:310,h:86,description:"The anchoring index is a descriptive ratio of the difference in group medians to the difference in anchors, calculated per item. The reported high/low comparison uses individual averages of transformed estimates. Confirm exact aggregation, pairing and missing-data rules before generating analysis code.",evidence:{page:3,rects:[{x:51.1,y:56.8,w:40.2,h:19.3}],quote:"There was a highly significant difference between individual averages of the transformed estimates made with high and low anchors, t(102) = 7.99, p < .01."},fields:[{name:"Descriptive estimand",value:"(median_high − median_low) / (anchor_high − anchor_low)",status:"reported"},{name:"Inferential input",value:"Individual averages of transformed estimates",status:"reported"},{name:"Reported result",value:"t(102) = 7.99, p < .01",status:"reported"},{name:"Execution contract",value:"Confirm aggregation, pairing and missing-data policy",status:"unresolved"}]},
 {"id": "reported-results", "kind": "result", "title": "Anchoring effect reported", "subtitle": "t(102) = 7.99 · p < .01", "description": "Observed results from the original study, separate from the analysis plan and from any future replication data.", "evidence": {"page": 3, "rects": [{"x": 51.1, "y": 56.8, "w": 40.2, "h": 19.3}], "quote": "There was a highly significant difference between individual averages of the transformed estimates made with high and low anchors, t(102) = 7.99, p < .01."}, "fields": [{"name": "Reported result", "value": "t(102) = 7.99, p < .01", "status": "reported"}, {"name": "Outcome", "value": "Individual averages of transformed estimates with high and low anchors.", "status": "reported"}], "x": 20, "y": 680, "w": 205, "h": 78},
 ],
 relations:[{from:"rationale",to:"analysis",label:"motivates"},{from:"confidence-prediction",to:"responses",label:"tests confidence relationships"},{from:"analysis",to:"reported-results",label:"reported findings"},{from:"people",to:"procedure",label:"acts in"},{from:"inputs",to:"procedure",label:"is presented in"},{from:"procedure",to:"responses",label:"produces"},{from:"responses",to:"manipulation",label:"carries"},{from:"responses",to:"outcome",label:"measures"},{from:"manipulation",to:"analysis",label:"defines contrast"},{from:"outcome",to:"analysis",label:"supplies outcome"}],
 procedure:[
 {id:"comparison",name:"Compare with anchor",actor:"Experimental participant",input:"item.question + version-specific anchor",output:"comparison: greater | less",evidence:trialEvidence},
 {id:"estimate-step",name:"Estimate the quantity",actor:"Same participant",input:"Current quantity, after comparison",output:"estimate: numeric, item-specific unit",evidence:trialEvidence},
 {id:"confidence-step",name:"Report confidence",actor:"Same participant",input:"The estimate just provided",output:"confidence: 10-point scale",evidence:{page:3,rects:[{x:8.9,y:51.8,w:39.5,h:1.6}],quote:"then they indicated their confidence in the estimate."}},
 ],
 variables:[
 {id:"pid",name:"participant_id",role:"Identifier",type:"ID",unit:"Participant",producedBy:"Recruitment",usedBy:"Link repeated observations",definition:"Stable identity across the 15 item responses.",status:"implementation",entity:"people"},
 {id:"iid",name:"item_id",role:"Identifier",type:"ID",unit:"Quantity / item",producedBy:"Stimulus set",usedBy:"Join units, anchors and calibration",definition:"Identifies which quantity was estimated.",status:"implementation",entity:"inputs"},
 {id:"version",name:"questionnaire_version",role:"Assignment",type:"Category",unit:"Participant",producedBy:"Version assignment",usedBy:"Determine per-item anchor",definition:"Two versions, each with high anchors for some items and low for others.",status:"reported",entity:"inputs"},
 {id:"level",name:"anchor_level",role:"Manipulation",type:"Low / high",unit:"Participant × item",producedBy:"Version × item mapping",usedBy:"High / low comparison",definition:"Not a permanent group label on a participant.",status:"reported",entity:"manipulation"},
 {id:"anchor-value",name:"anchor_value",role:"Stimulus parameter",type:"Number",unit:"Item-specific units",producedBy:"Calibration percentiles × version mapping",usedBy:"Comparison prompt; anchoring-index denominator",definition:"The displayed numerical anchor, separate from its low/high label.",status:"reported",entity:"inputs"},
 {id:"comparison",name:"comparison",role:"Observed response",type:"Greater / less",unit:"Participant × item",producedBy:"Comparison step",usedBy:"Preserve the response sequence",definition:"The comparison judgment before the numerical estimate.",status:"reported",entity:"responses"},
 {id:"estimate",name:"estimate",role:"Observed outcome",type:"Number",unit:"Participant × item",producedBy:"Estimation step",usedBy:"Percentile transform, medians",definition:"Raw estimate; unit depends on the question.",status:"reported",entity:"responses"},
 {id:"confidence",name:"confidence",role:"Observed response",type:"10-point scale",unit:"Participant × item",producedBy:"Confidence step",usedBy:"Confidence analysis; details to review",definition:"Keep separate from estimate and comparison.",status:"reported",entity:"responses"},
 {id:"percentile",name:"estimate_percentile",role:"Derived outcome",type:"Number · 0–100",unit:"Participant × item",producedBy:"Item-specific calibration distribution",usedBy:"Individual averages → contrast",definition:"Percentile transform with out-of-range scores assigned 0 or 100.",status:"reported",entity:"outcome"},
 {id:"mean-percentile",name:"mean_percentile_by_anchor",role:"Aggregated outcome",type:"Number",unit:"Participant × anchor level",producedBy:"Individual averages of transformed estimates",usedBy:"Reported high / low contrast",definition:"Exact item pooling, missing-data rules and test pairing still require review.",status:"unresolved",entity:"analysis"},
 {id:"ai",name:"anchoring_index",role:"Descriptive statistic",type:"Ratio",unit:"Item",producedBy:"Group medians and anchors",usedBy:"Descriptive anchoring effect",definition:"Difference in anchored medians divided by difference in anchors.",status:"reported",entity:"analysis"},
 ]
};
