"use client";
import { createContext, useContext } from "react";
export type Language = "en" | "zh";
export const LanguageContext = createContext<Language>("en");
const zh: Record<string,string> = {
 "Select objects":"选择对象", "Circle selection":"圈选",
 "Workspace views":"工作区视图", "Artifact views":"内容视图", "Show / hide conversation":"显示 / 收起对话", "Split view":"分屏对照", "Layout":"布局", "Conversation + model":"对话 + 模型", "Conversation + source":"对话 + 原文", "Reset panel widths":"恢复面板宽度", "Focus panel":"放大面板", "Close panel":"收起面板", "Focus":"放大", "Restore":"还原", "Restore layout":"恢复布局", "Commands":"快捷命令", "Workspace commands":"工作区命令", "Search commands":"搜索命令", "Search commands…":"搜索视图与操作…", "No matching commands":"没有匹配的命令", "Navigate":"选择", "Choose":"执行", "Focus conversation":"回到对话", "View study model":"查看研究模型", "View sources and resources":"查看原文与材料", "Compare source and model":"对照原文与模型", "Focus study model":"放大研究模型", "Focus original source":"放大论文原文", "Conversation history":"会话历史", "Example · AI offline":"示例 · AI 离线",
 "Experiment overview":"实验总览", "Proposed changes · preview":"修改提案 · 预览", "Added":"新增", "Changed":"修改", "Proposed change":"提议改动", "Study part":"研究组成", "Question":"待确认", "question":"项待确认", "questions":"项待确认", "questions for":"项问题对应", "open questions":"项待确认", "All questions →":"全部待确认 →", "Answer in conversation ↗":"在左侧讨论 ↗", "Study title or source changed":"研究名称或来源发生变化", "Procedure sequence changed":"实验流程顺序发生变化",

 "Add a paper":"添加论文", "Retry response":"重试回答", "Sync study package":"同步研究包", "study":"研究整体",
 "Next decision":"下一项决定", "Answers saved · awaiting changes":"回答已保存 · 待落实", "Answered · not yet applied":"已回答 · 待落实", "Why this needs a decision":"查看影响与依据", "View source":"查看原文", "Give a decision":"提供决定", "Discuss":"讨论", "Later":"稍后", "All decisions":"全部待确认事项", "You can return to these decisions whenever you are ready.":"这些事项已暂放，随时可以继续。", "Your answers are saved. Review the agent’s proposed changes before they become part of the study.":"回答已保存。确认助手的修改提案后，才会落实到研究中。", "Help me decide:":"帮我讨论这个决定：", "Your decision":"你的研究决定", "Proposed changes":"修改提案", "Changes accepted":"修改已接受", "Changes set aside":"修改已暂放", "Removed":"移除", "Return to current study":"回到当前研究", "Preview changes":"预览改动", "What changes":"查看具体变化", "Accept changes":"接受修改", "Continue discussing":"继续讨论", "Set aside":"暂不采用", "Let’s discuss these proposed changes.":"我们继续讨论这个修改提案。", "Reply / side talk":"回复 / 单独讨论", "Export study ↗":"导出研究包 ↗", "Agent is reviewing your request…":"助手正在处理你的请求…", "Thinking…":"思考中…", "Preparing study package…":"正在同步研究包…", "Study package ready":"研究包已就绪", "Review changes to continue":"有修改待确认", "Study package needs updating":"研究包需要同步", "Study package could not sync":"研究包同步失败", "Preparing the first study…":"正在提取初始研究…", "entities":"研究对象", "relations":"对象关系", "procedure":"实验流程", "variables":"统计变量", "reviewIssues":"待确认事项", "title":"研究名称",

 "Study source":"研究资源",
 "No source yet":"尚未添加资源",
 "Paper":"论文",
 "Resource":"资源",
 "Uploading…":"上传中…",
 "+ Paper":"+ 论文",
 "+ Resource":"+ 资源",
 "Download original":"下载原文件",
 "Drag to resize · double-click to reset widths":"拖动调宽 · 双击恢复宽度", "Source & resources":"原文与材料", "All views":"全部视图", "Resize panels":"调整面板宽度", "Collapse source":"收起原文", "Collapse study model":"收起研究模型", "agent":"Agent", "source":"原文", "model":"模型", "Blocking":"阻塞项", "Decision":"研究者选择", "Check":"待核查", "Source pointer":"原文位置", "Reason":"原因", "Suggested next step":"建议下一步", "Study":"研究", "Field":"字段",
 "Original resource":"原始材料",
 "Research resource":"研究资源",
 "Loading resource…":"加载资源中…",
 "Raw file preview. Content is not interpreted or executed.":"原始文件预览。",
 "Original image preview.":"原始图片。",
 "ZIP directory only. File contents are supplied to the build worker; no analysis is shown here.":"ZIP 文件目录；其中的材料会传给构建助手。",
 "Inline preview is unavailable for this file type. The original file is retained for download and passed to the study-building worker as a research resource. It is not executed.":"此格式暂不支持预览，可下载原文件；文件会作为研究材料传给构建助手。",
 "The preview is truncated. Download the original to inspect all content.":"预览已截断，下载原文件可查看完整内容。",
 "Selected PDF is the primary paper for the next build.":"当前 PDF 是下一次构建的主论文。",
 "Build resources are limited to 20 MB combined.":"附加构建材料合计上限为 20 MB。",
 "Use highlight or box on scanned pages":"扫描页可用高亮或框选标记",
 "Use this side-talk message in our main study:":"将这条分支讨论中的消息作为主线研究的上下文：",
 "Source not located":"尚未定位原文证据",
 "Resources":"研究资源", "Zoom in":"放大", "Zoom out":"缩小", "Highlight":"高亮", "Save highlight":"保存标记", "Highlighted passage":"高亮原文", "Marked region":"标记区域",
 "Reply":"回复此处", "Side talk":"分支讨论", "Main conversation":"主线", "Parent conversation":"上一级讨论", "Bring to main":"带回主线", "Clear reply":"取消消息引用",
 "Brought from a side talk":"从分支带回", "Reply to an earlier message":"回复之前的消息",

 "Study workspace":"研究工作区", "files":"份文件", "Materials":"材料", "Study materials":"研究材料", "Research draft":"研究草稿", "Download material":"下载材料", "Review materials":"查看材料提案", "About this material":"关于这份材料",
 "Ask the agent to draft instructions, a questionnaire or an analysis plan.":"请助手起草参与者指引、问卷或分析方案。",
 "Upload a paper to begin.":"上传论文，开始研究。",
 "Upload a paper, then ask the agent to build the first model.":"上传论文，与助手一起生成研究模型。",
 "Proposed materials":"材料修改提案", "Proposed model":"模型修改提案", "Review proposed model":"查看提案内容",
 "Apply":"应用", "Reject":"暂不采用", "pending":"待确认", "applied":"已应用", "rejected":"未采用",
 "Working…":"正在处理…", "Saved":"已保存", "Saving…":"正在保存…", "Unsaved changes":"待保存", "Not saved":"未保存",
 "Unlink object":"取消对象关联", "No linked object":"暂不关联对象", "Original PDF · text & regions":"原始 PDF · 选字与框选",
 "Saved to your account":"保存在你的账号中", "Conversations and annotations are saved to your account.":"会话和批注保存在你的账号中。",
 "Workspace clicks, timing, pointer movement and AI conversations are recorded for platform research.":"工作区的点击、操作时间、鼠标轨迹和 AI 会话将记录用于平台研究。",
 "No open questions":"暂无待确认问题", "Recorded observations":"观测记录",
 "Questions linked to the affected part of the study.":"问题关联到对应的研究对象。",
 "Response saved. Discuss it with the agent to update the model.":"回答已保存，可与助手讨论并更新模型。",
 "Let’s build your study.":"一起构建研究。",
 "Select a passage or a part of the model.":"选择原文或模型中的内容。",
 "Saved with references · AI offline.":"已保存引用 · AI 尚未连接",
 "The earlier extraction treated high / low anchor as a participant group. The revised model attaches it to each item in a questionnaire version. Is this correction right?":"之前的提取把高 / 低锚点当作参与者分组。当前模型改为按问卷中的每个题目记录，这个修正是否正确？",
 "Changes the assignment model, response keys and high / low comparison.":"影响分配方式、回答记录及高 / 低锚点的比较。",
 "Confirm the item-level interpretation; keep participant identity across both anchor levels.":"核对题目层面的解释，保留同一参与者在不同锚点水平下的身份关联。",
 "The linked passage describes two questionnaire versions, but does not specify how participants receive a version. What should the implementation do?":"原文说明有两个问卷版本，但没有说明如何分配给参与者。实现时应该采用什么方案？",
 "Blocks a complete assignment procedure. Random allocation must not be silently assumed.":"分配流程尚不完整，不能直接假定为随机分配。",
 "Check additional materials, or specify a researcher decision and label it separately from the paper.":"查阅补充材料，或明确研究者决定，并与原文报告分开标注。",
 "The paper reports a contrast of individual average percentile scores. Confirm the exact pooling, pairing and missing-response policy before producing analysis code.":"论文比较了个人平均百分位分数。生成分析代码前，还需要确认汇总、配对与缺失回答的处理方式。",
 "Determines the rows and values entering the test, and whether incomplete observations are included.":"决定检验使用哪些记录，以及是否纳入不完整观察。",
 "Review the source and specify these choices explicitly. A reported t statistic alone is not an executable analysis plan.":"对照原文明确这些选择。仅有报告的 t 统计量还不足以形成可执行的分析方案。",
 "Who takes part":"参与者",
 "What they receive":"输入材料",
 "What happens, in order":"实验流程",
 "What gets recorded":"输出记录",
 "Which comparison is made":"分析比较",
 "Population":"人群",
 "Calibration sample":"校准样本",
 "Experimental sample":"实验样本",
 "Participant identity":"参与者标识",
 "Input record":"输入记录",
 "Anchor construction":"锚点构建",
 "Version mapping":"版本映射",
 "Version allocation":"版本分配",
 "Actor":"执行者",
 "Repeats over":"重复范围",
 "Visible input":"可见输入",
 "Steps":"步骤",
 "Grain":"记录单位",
 "Keys":"关联键",
 "Observed responses":"原始回答",
 "Preserve":"保留",
 "Statistical role":"统计角色",
 "Type / levels":"类型 / 水平",
 "Unit of variation":"变化单位",
 "Observed value":"观测值",
 "Derived value":"派生值",
 "Reference":"参照",
 "Transformation":"转换",
 "Descriptive estimand":"描述性目标量",
 "Inferential input":"推断输入",
 "Reported result":"报告结果",
 "Execution contract":"执行方案",
 "Collapse agent":"收起助手",
 "Expand agent":"展开助手",
 "Message study agent":"给研究助手发送消息",
 "Send message":"发送消息",
 "Previous page":"上一页",
 "Next page":"下一页",
 "Source zoom":"原文缩放",
 "Selectable OCR text":"可选择的 OCR 文字",
 "Close annotations":"关闭批注",
 "Cancel selection":"取消选区",
 "Annotation linked object":"批注关联对象",
 "Close comment":"关闭批注",
 "Return to full study overview":"回到研究总览",
 "Close review queue":"关闭待核对列表",
 "Clear model selection":"取消模型选区",
 "Ask AI about model selection":"针对模型选区提问",
 "Send model prompt":"发送选区问题",
 "Build Study":"构建研究", "Study agent":"研究助手", "Study model":"研究模型", "Original paper":"论文原文", "Export draft ↗":"导出 ↗", "History":"历史会话", "New chat":"新会话", "Settings":"设置", "Close":"关闭", "Appearance":"外观", "Language":"界面语言", "System":"跟随系统", "Light":"浅色", "Dark":"深色", "Saved on this device":"保存在此设备", "Conversations, annotations and preferences are stored in this browser.":"会话、批注和偏好保存在当前浏览器中。", "Source quotations stay in their original language.":"原文引用保留原语言。", "No conversations yet":"还没有会话", "Untitled conversation":"新会话", "Ask about your study…":"讨论这项研究…", "Select something to begin":"选中内容，开始讨论", "Paper → selection → conversation":"原文 → 选区 → 对话", "Model → circle → conversation":"模型 → 圈选 → 对话", "Demo agent":"演示助手", "Shared with chat":"已关联对话", "Return to selection":"回到选区", "Clear context":"取消引用", "Source selection":"原文选区", "Circled region":"圈选区域", "Model selection":"模型选区", "objects":"个对象", "Ask AI":"问 AI", "Comment":"批注", "Comments":"批注", "Add comment":"保存批注", "Annotations":"批注", "No annotations yet":"暂无批注", "Text":"选字", "Box":"框选", "Fit width":"适合宽度", "Drag over text or draw a box":"拖选文字 · 框选区域", "Selected passage":"所选文字", "Box selection":"框选区域", "Link to":"关联", "Add a note…":"写下批注…", "Discuss with agent ↗":"发到对话 ↗", "Add another comment":"继续批注", "Source link":"原文关联", "Your annotation":"你的批注", "Loading original pages…":"正在载入原文…", "Scanned PDF · selectable OCR":"扫描原文 · 可选文字", "Overview · source-linked draft":"总览 · 原文关联", "Need input":"待确认", "↖ Select":"↖ 选择", "◯ Circle to ask":"◯ 圈选", "⌂ Overview":"⌂ 总览", "What needs your judgment":"需要你确认", "Review examples · linked to the affected part of the study.":"问题与对应的研究对象关联。", "Response saved · pending application":"已保存 · 待应用", "Interpretation":"理解核对", "Missing information":"信息缺失", "THE STUDY AT A GLANCE":"研究总览", "How much do numerical anchors shift estimates?":"数值锚点如何影响估计？", "Compare estimates made after low and high anchors, using a separate calibration sample as the reference.":"以独立校准样本为基准，比较高、低锚点下的估计。", "Draw a loop around anything you want to discuss.":"圈住想讨论的内容", "Click to inspect or ask · Shift-click to select several · Circle a region":"点击查看 · Shift 多选 · 圈选讨论", "Prepare the study":"准备研究", "People + materials":"参与者 + 材料", "Run a participant session":"进行实验", "Input → person → output":"输入 → 人 → 输出", "Keep the observations":"记录观察", "One record per participant × item":"每位参与者 × 每个题目一条记录", "Turn observations into evidence":"分析证据", "Derive → compare":"转换 → 比较", "Participants":"参与者", "53 calibration · 103 experimental":"53 校准 · 103 实验", "Separate samples · Berkeley students":"独立样本 · 伯克利学生", "Questionnaires":"问卷", "15 quantities · 2 versions":"15 个题目 · 2 个版本", "Same item order across versions":"各版本题序一致", "Low / high anchor":"低 / 高锚点", "Varies by item within a version":"同一版本内随题目变化", "Manipulation · participant × item":"操纵变量 · 参与者 × 题目", "Compare → estimate → confidence":"比较 → 估计 → 信心", "One participant repeats this sequence for 15 quantities.":"每位参与者完成 15 个题目。", "Input: item + anchor → Output: 3 responses":"输入：题目 + 锚点 → 输出：3 项回答", "Response record":"回答记录", "Comparison · estimate · confidence":"比较判断 · 估计值 · 信心", "Linked to participant, item and version":"关联参与者、题目与版本", "Calibrate the estimate":"校准估计值", "Raw estimate → percentile":"原始估计 → 百分位", "Reference: same item's calibration sample":"参照：该题的校准样本", "Compare low / high":"比较低 / 高锚点", "Average percentiles + anchoring index":"平均百分位 + 锚定指数", "Analysis choices need review":"分析方案待确认", "Check the unit of manipulation":"核对操纵单位", "How are versions allocated?":"如何分配问卷版本？", "Define the analysis contract":"明确分析方案", "Source-linked draft":"关联原文的草稿", "Click a card to inspect evidence, steps and variables.":"点击卡片查看证据、步骤与变量。", "Why it matters":"影响", "Evidence & suggested next step":"证据与建议", "Your correction or decision":"你的修正或决定", "Describe the correction, supply evidence, or specify a study decision…":"补充证据、修正理解或指定研究方案…", "Discuss with AI ↗":"与 AI 讨论 ↗", "Save response":"保存回答", "✓ Response saved · pending application to the program":"✓ 已保存 · 待应用到程序", "Hide details ↑":"收起详情 ↑", "Inspect details ↓":"查看详情 ↓", "Flag an error":"指出问题", "Reported in source":"原文已报告", "Implementation proposal":"实现建议", "Needs review":"待核对", "Inside one trial":"单次实验", "Input":"输入", "Person":"参与者", "Output":"输出", "Variables used here":"相关变量", "Review →":"核对 →", "All review questions answered":"核对问题均已回答", "decisions need input":"项待确认", "pending application":"项待应用", "Canvas region · your drawing is attached":"已引用画布选区", "Ask about this circled region…":"讨论这个圈选区域…", "Ask, correct, or describe a change to this selection…":"针对选区提问或提出修改…", "Selection + source references travel with your prompt.":"选区与原文引用将一起发送。", "Sent with this selection. Reply is in Study agent.":"已发送到左侧对话。", "Locate original evidence":"定位原文", "Review question sent with the issue and its source evidence.":"问题与原文证据已发送到对话。", "Response saved locally. Applying it to the program still needs the live agent.":"回答已保存，待接入助手后应用。", "I think there is an error here: ":"这里可能有误：", "Compare with anchor":"与锚点比较", "Estimate the quantity":"估计数值", "Report confidence":"报告信心", "Overview":"总览", "Details":"详情", "Use selection":"引用选区", "Restore context":"恢复引用", "Rename conversation":"重命名会话", "Save":"保存", "Cancel":"取消", "Search conversations…":"搜索会话…", "No matching conversations":"没有匹配的会话", "Review":"核对", "Source":"原文", "Model":"模型", "Keyboard shortcuts":"快捷键", "Send":"发送", "New line":"换行", "Clear selection / close":"取消选区 / 关闭", "The live agent is not connected. Your message and references are saved in this conversation.":"尚未连接真实助手。你的消息和引用已保存在此会话中。"
};
export const translator=(language:Language)=>(text:string)=>language==="zh"?(zh[text]??text):text;
export function useT() { return translator(useContext(LanguageContext)); }
export function HubMark({size=26}:{size?:number}) { return <svg width={size} height={size} viewBox="0 0 32 32" fill="var(--accent,#247c91)" aria-hidden="true"><path d="M5 4h6v9h7l-3 6h-4v9H5V4Zm16 0h6v24h-6v-9h-4l3-6h1V4Z"/></svg>; }
export function UiIcon({name,size=16}:{name:"history"|"new"|"settings"|"panel"|"source"|"circle"|"selection";size?:number}) {
 const paths={
  history:<><path d="M3 9a7 7 0 1 1 1 8M3 4v5h5"/><path d="M12 8v4l3 2"/></>,
  new:<><path d="M12 5v14M5 12h14"/></>,
  settings:<><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2" fill="var(--surface,#fff)"/><circle cx="15" cy="17" r="2" fill="var(--surface,#fff)"/></>,
  panel:<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/></>,
  source:<><path d="M14 3H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8Z"/><path d="M14 3v5h5M9 12h6M9 16h6"/></>,
  circle:<path d="M19 6c-4-4-12-3-15 2s-1 11 5 12 12-3 12-8c0-3-2-5-5-6"/>,
  selection:<><path d="M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5"/><path d="M8 12h8"/></>
 };
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
